# Cross-compile changes by Thomas E. Hansen (CodingCellist) 2021-03-08

# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PTHREAD_MACROS_DIR := $(BASEDIR)/pthread_macros
MACROS := $(BASEDIR)/pthread_macros/pthread.m4.stougie

CC := $(TOOLCHAIN_PREFIX)gcc
CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -std=c11 -g -fno-strict-aliasing -I$(PTHREAD_MACROS_DIR)
LDFLAGS := -lm


M4 := m4 -Ulen -Uindex
OBJS += zsim_hooks.o

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

%.h: %.h.in
	$(M4) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<

zsim_hooks.o: $(PTHREAD_MACROS_DIR)/zsim_hooks.c \
              $(PTHREAD_MACROS_DIR)/zsim_hooks.h
	$(CC) $(CFLAGS) -c $< -o $@


